FROM ubuntu:focal

RUN apt update && apt install -y git make bash curl unzip

ENV FLUTTER_HOME=${HOME}/sdks/flutter \
  FLUTTER_VERSION="3.3.6"
ENV FLUTTER_ROOT=$FLUTTER_HOME

ENV PATH ${PATH}:${FLUTTER_HOME}/bin:${FLUTTER_HOME}/bin/cache/dart-sdk/bin

RUN git clone --branch ${FLUTTER_VERSION} https://github.com/flutter/flutter.git ${FLUTTER_HOME}

RUN flutter doctor \
  && chown -R root:root ${FLUTTER_HOME} \
  && flutter precache --web --no-android --no-ios --no-universal