const STUDYPLAN_MODIFIER_SERVICE = 'eureka.v1.StudyPlanModifierService';

export const STUDYPLAN_MODIFIER_UPSERT_RESOURCE = 'UpsertStudyPlan';

export const UPSERT_STUDYPLAN_ENDPOINT = `${STUDYPLAN_MODIFIER_SERVICE}/${STUDYPLAN_MODIFIER_UPSERT_RESOURCE}`;
