const COURSE_MODIFIER_SERVICE = 'yasuo.v1.CourseModifierService';

export const COURSE_MODIFIER_SERVICE_UPSERT_QUIZ = 'UpsertQuizV2';

export const UPSERT_QUIZ_ENDPOINT = `${COURSE_MODIFIER_SERVICE}/${COURSE_MODIFIER_SERVICE_UPSERT_QUIZ}`;
