name: Run record test

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Pull Metadata
      id: run-recorder
      run: |
          yarn add @playwright/test
          npx playwright test test-suites/squads/architecture/step-definitions/management-configuration.ts