name: Run record test

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Checkout
      uses: actions/checkout@v1

    - name: Pull Metadata
      id: run-recorder
      run: |
          npx playwright test test-suites/squads/architecture/step-definitions/management-configuration.ts