name: dummy_workflow

on:
  workflow_dispatch:
    inputs:
      user_input:
        required: true
        default: "Hello, world."

jobs:
  log-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log( ${{ inputs.user_input }} )