name: tiered.post-merge

on:
  push:
    branches:
      - develop

env:
  GITHUB_TOKEN: ${{ secrets.BUILD_GITHUB_TOKEN }}

permissions:
  contents: "read"
  id-token: "write"
 
jobs:
  runners:
    runs-on: ['self-hosted', '60m-240mi', 'spot', 'persistent']
    outputs:
      runners: ${{ steps.runners.outputs.runners }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop #should be develop
          repository: manabie-com/backend
          token: ${{ secrets.BUILD_GITHUB_TOKEN }}

      - id: runners
        uses: ./.github/actions/runners
        with:
          repo: 'eibanam'
          workflow: 'tiered.post-merge'

  run-e2e:
    runs-on: ${{ fromJson(needs.runners.outputs.runners)['run-e2e'] }}
    needs: [runners]
    timeout-minutes: 100
    steps:
      - uses: manabie-com/workflow-telemetry-action@v1
        continue-on-error: true
        with:
          comment_on_pr: false

      - uses: actions/checkout@v3
      - name: run-e2e
        uses: ./.github/actions/reuse.e2e
        timeout-minutes: 90
        with:
          EIBANAM_REF: "develop"
          FE_REF: ""
          ME_REF: ""
          TAGS: "@critical"
          FEATURE_FILES: ""
          ENV: "staging"
          ORGANIZATION: "manabie" #TODO: add JPREP later
          DURATION_LIMIT: 3000000 # 50 mins
          RUN_ID: ${{ github.run_id }}

          REPO: "eibanam"
          OWNER: ${{ github.actor }}
          ISSUE_NUMBER: ""

          GCR_JSON_KEY: ${{ secrets.GCR_JSON_KEY }}
          BUILD_GITHUB_TOKEN: ${{ secrets.BUILD_GITHUB_TOKEN }}
          OTLP_ACCESS_TOKEN: ${{ secrets.OTLP_ACCESS_TOKEN }}
          REPORT_HASURA_SECRET: ${{ secrets.REPORT_HASURA_SECRET }}
          UNLEASH_CLIENT_KEY: ${{ secrets.UNLEASH_CLIENT_KEY }}
          UNLEASH_CREDENTIAL: ${{ secrets.UNLEASH_CREDENTIAL }}
          FAIL_FAST: true

      - name: cleanup cucumber #because we can't add timeout in composite action
        if: always()
        timeout-minutes: 5
        run: |
          ./scripts/docker-compose.sh web_profile
        shell: bash
