export const NOTIFICATION_SERVICE = 'notificationmgmt.v1.NotificationModifierService';

export const NOTIFICATION_UPSERT_RESOURCE = 'UpsertNotification';
export const NOTIFICATION_SEND_RESOURCE = 'SendNotification';
export const NOTIFICATION_DISCARD_RESOURCE = 'DiscardNotification';

export const UPSERT_NOTIFICATION_ENDPOINT = `${NOTIFICATION_SERVICE}/${NOTIFICATION_UPSERT_RESOURCE}`;

export const SEND_NOTIFICATION_ENDPOINT = `${NOTIFICATION_SERVICE}/${NOTIFICATION_SEND_RESOURCE}`;
export const DISCARD_NOTIFICATION_ENDPOINT = `${NOTIFICATION_SERVICE}/${NOTIFICATION_DISCARD_RESOURCE}`;
